CREATE TABLE IF NOT EXISTS role (
    id INT NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO role (id, name)
VALUES (1, 'ROLE_ADMIN')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO role (id, name)
VALUES (2, 'ROLE_NORMAL')
ON DUPLICATE KEY UPDATE name = VALUES(name);

